spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maybank
    username: maybank
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080